# Generated by Django 3.0.8 on 2020-07-17 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_somemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SomeModel',
        ),
    ]
